routes/web.php
    Route::post('checkout', [\App\Http\Controllers\CartController::class, 'checkoutPost'])->name('checkout.post');
});
*/

Route::get('/cart', [\App\Http\Controllers\CartController::class, 'index'])->name('cart.index');
Route::post('/cart', [\App\Http\Controllers\CartController::class, 'add'])->name('cart.add');
Route::post('/cart/checkout', [\App\Http\Controllers\CartController::class, 'checkoutPost'])->name('cart.checkout.post');
Route::get('/cart/checkout', [\App\Http\Controllers\CartController::class, 'checkout'])->name('cart.checkout.index');

/* End Cart */









Route::get('payment_success', function (Request $request) {
    
    session()->forget('cart');
    session()->forget('cartID');

    return view('paymentsuccess');
})->name('paymentsuccess');

Route::get('payment_error', function (Request $request) {

    print_r($request->all());
    return view('paymenterror');
})->name('paymenterror');



Route::post('payment_callback', function (Request $request) {
    $merchant_key     = 'rq2Ckdh3zzcWS2Ss';
    $merchant_salt    = '7Pd2undrARfxhz4A';

    $hash = base64_encode(hash_hmac('sha256', $request->input('merchant_oid') . $merchant_salt . $request->input('status') . $request->input('total_amount'), $merchant_key, true));

    if ($hash != $request->input('hash')) {
        die('PAYTR notification failed: bad hash');
    }

    if ($request->input('status') == 'success') {
        $trans_id = preg_replace("/[a-zA-Z\s-]/", "", $request->input('merchant_oid'));
        $transaction = Transaction::where('id', $trans_id)->where('status', 'pending')->first();

        if($transaction){

            $cart = Cart::find($transaction->cart_id);
            if($cart) {

                $tiedUser = User::where('email', $cart->email)->first();
                //create user
                if (!$tiedUser) {
                    $randPass = Str::random(10);
                    $user = User::create([
                            'name' => $cart->full_name,
                            'email' => $cart->email,
                            'password' => Hash::make($randPass),
                        ]);
                    $userId = $user->id;

                    UserManuallyCreated::dispatch($cart->email, $randPass);
                    OrderCreated::dispatch($cart->email);
                } else {
                    OrderCreated::dispatch($cart->email);
                    $userId = $tiedUser->id;
                }
                $order = new Order;

                $order->user_id       = $userId;
                $order->email         = $cart->email;
                $order->full_name     = $cart->full_name;
                $order->phone_number  = $cart->phone_number;

                $order->queue_type    = $cart->queue_type;
                $order->boost_type    = $cart->boost_type;
                $order->wins          = $cart->wins;
                $order->current_rank  = $cart->current_rank;
                $order->current_lp    = $cart->current_lp;
                $order->desired_rank  = $cart->desired_rank;

                $order->summoner_name = $cart->summoner_name;
                $order->lol_username      = $cart->lol_user;
                $order->lol_password      = $cart->lol_pass;

                $order->server        = $cart->server;
                $order->price         = ($request->input('payment_amount') / 100);

                $order->save();

                $orderExtras = new OrderExtra;
                $orderExtras->order_id     = $order->id;
                $orderExtras->role1        = $cart->role1;
                $orderExtras->role2        = $cart->role2;
                $orderExtras->spell1       = $cart->spell1;
                $orderExtras->spell2       = $cart->spell2;
                $orderExtras->champions    = $cart->champions;

                $orderExtras->save();

                $cart->delete();
                $transaction->status = "completed";
                $transaction->save();
            }
        }
    } else if($request->input('status') == "failed") {
        $trans_id = preg_replace("/[a-zA-Z\s-]/", "", $request->input('merchant_oid'));
        $transaction = Transaction::where('id', $trans_id)->where('status', 'pending')->first();
        if($transaction) {

            //email them about failure

            if($request->input('failed_reason_code') == 6) {
                $transaction->status = "abandoned";
                $transaction->status_number = $request->input('failed_reason_code');
                $transaction->save();
            }else {
                $transaction->status = "failed";
                $transaction->status_number = $request->input('failed_reason_code');
                $transaction->save();
            }
        }
    }

    return response('OK', 200);
    
});


Route::get('/m/{boostId}', [\App\Http\Controllers\ChatsController::class, 'getMessages'])->name('boostMessaging');
//Route::get('messages/{boostId}', [\App\Http\Controllers\ChatsController::class, 'fetchMessages']);
Route::post('messages/{boostId}', [\App\Http\Controllers\ChatsController::class, 'sendMessage']);



Route::get('/demopage', function () {
    return view('demopage');
})->name('demopage');

Route::get('/open_orders', function () {
    return view('open_orders');
})->name('open_orders');

Route::get('/ongoing_orders', function () {
    return view('ongoing_orders');
})->name('ongoing_orders');

Route::get('/finished_orders', function () {
    return view('finished_orders');
})->name('finished_orders');

Route::get('/demo_page_chat', function () {
    return view('demo_page_chat');
})->name('demo_page_chat');


/*
Route::get('/checkout/userinfo', function(Request $request) {


    $request->session()->reflash();

    if($request->old('serializedState')){
        $request->session()->flash('serializedState', $request->old('serializedState'));
    }
    

    return view('checkout-userinfo')->with([
        'serializedState' => $request->session()->get('serializedState'),
        'duoSelected' => $request->session()->get('duoSelected'),
    ]);
});
Route::post('/checkout/userinfo', [\App\Http\Controllers\CalculatorController::class, 'checkoutUserInfo'])->name('checkout.userinfo');
Route::post('/checkout', [\App\Http\Controllers\CalculatorController::class, 'checkoutPost'])->name('checkout.submit');
Route::get('/checkout', [\App\Http\Controllers\CalculatorController::class, 'checkout'])->name('checkout');

*/

Route::middleware(['auth'])->group(function() {

    //dashboard home
    Route::get('/dashboard', function () {
        return view('dashboard.index');
    })->name('dashboard.home');

    Route::middleware('role:normal')->group(function() {
        Route::get('orders', [\App\Http\Controllers\OrderController::class, 'index'])->name('orders.index');
    });

    //all admin routes
    Route::prefix('admin')->name('admin.')->middleware(['role:admin'])->group(function() {

        //order routes
        Route::get('orders/{order}/delete', [\App\Http\Controllers\Admin\OrderController::class, 'delete'])->name('orders.delete');
        Route::get('orders/finished', [\App\Http\Controllers\Admin\OrderController::class, 'finished'])->name('orders.finished');
        Route::get('orders/{order}/assign', [\App\Http\Controllers\Admin\OrderController::class, 'assign'])->name('orders.assign');
        Route::post('orders/{order}/assign', [\App\Http\Controllers\Admin\OrderController::class, 'assignSubmit'])->name('orders.assign.submit');
        Route::resource('orders', \App\Http\Controllers\Admin\OrderController::class);
        //end order routes

        //list all ongoing boosts
        Route::get('boosts', [\App\Http\Controllers\Admin\BoostsController::class, 'index'])->name('boosts.index');
        Route::patch('boosts/{boost}/takeaway', [\App\Http\Controllers\Admin\BoostsController::class, 'takeaway'])->name('boosts.takeaway');

        Route::get('user-management', [\App\Http\Controllers\Admin\UserManagementController::class, 'index'])->name('user-management.index');

        Route::get('financial', [\App\Http\Controllers\Admin\FinancialController::class, 'index'])->name('financial.index');
        Route::get('financial/{user}/edit', [\App\Http\Controllers\Admin\FinancialController::class, 'edit'])->name('financial.edit');
        Route::patch('financial/{user}', [\App\Http\Controllers\Admin\FinancialController::class, 'update'])->name('financial.update');

        //user Routes
        Route::get('user-roles', [\App\Http\Controllers\Admin\UserRolesController::class, 'index'])
           ->name('user-roles.index');
        Route::get('user-roles/{user}/edit', [\App\Http\Controllers\Admin\UserRolesController::class, 'edit'])
           ->name('user-roles.edit');
        Route::patch('user-roles/{user}', [\App\Http\Controllers\Admin\UserRolesController::class, 'update'])
           ->name('user-roles.update');
    });
    //end admin routes


    //all booster routes
    Route::prefix('booster')->name('booster.')->middleware('role:booster')->group(function() {
       Route::get('financial', function() {
           return view('dashboard.booster.financial.index');
       })->name('financial.index');

       Route::get('orders', [\App\Http\Controllers\Booster\OrderController::class, 'index'])->name('orders.index');
       Route::post('orders', [\App\Http\Controllers\Booster\OrderController::class, 'store'])->name('orders.store');
       Route::get('orders/ongoing', [\App\Http\Controllers\Booster\OrderController::class, 'ongoingOrders'])->name('orders.ongoing');
       Route::patch('orders/{order}/cancel', [\App\Http\Controllers\Booster\OrderController::class, 'cancel'])->name('orders.cancel');
       Route::patch('orders/{order}/finish', [\App\Http\Controllers\Booster\OrderController::class, 'finish'])->name('orders.finish');
       Route::get('orders/finished', [\App\Http\Controllers\Booster\OrderController::class, 'finished'])->name('orders.finished');
    });

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard/index.blade.php
<x-app-layout>
    <x-slot name="header">
            Dashboard
    </x-slot>


    You're logged in!

</x-app-layout>

resources/views/dashboard/orders-assign.blade.php
<x-app-layout>
    <x-slot name="header">
            Orders > Assign
    </x-slot>


    @if (session('status'))
        <div class="row">
            <div class="col-xl-12 col-md-12 mb-4">
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            </div>
        </div>
    @endif

    <div class="row">
        <!-- DataTales Example -->
        <div class="card shadow col-xl-10 col-md-6 mb-4 px-0 mx-3">
            <div class="card-header py-3 d-flex justify-content-between align-items-baseline">
                <h6 class="m-0 font-weight-bold text-primary">Open Orders</h6>
                <a href="{{ route('admin.orders.create') }}" class="btn btn-primary">Create Order</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Booster</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Booster</th>
                            <th>Actions</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @foreach($boosters as $booster)
                        <tr class="tableVisibleRow">
                            <td>{{ $booster->name }}</td>
                            <td>
                            <form method="post" action="{{ route('admin.orders.assign.submit', ['order' => $orderID]) }}">
                                @csrf
                                <input type="hidden" name="booster_id" value="{{ $booster->id }}" />
                                <input type="submit" class="btn btn-outline-success btn-sm" value="Give" />
                            </form>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

</x-app-layout>

resources/views/dashboard/orders-delete.blade.php
<x-app-layout>
    @push('styles')
        <style>
            .tableHiddenRow, .tableHiddenRow + tr {
                display: none;
            }
        </style>
    @endpush
    <x-slot name="header">
            Delete Order
    </x-slot>


    <div class="row">
        <!-- DataTales Example -->
        <div class="card shadow col-xl-10 col-md-6 mb-4 px-0 mx-3">
            <div class="card-header py-3 d-flex justify-content-between align-items-baseline">
                <h6 class="m-0 font-weight-bold text-primary">Delete Order</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Date</th>
                            <th>Queue</th>
                            <th>Boost</th>
                            <th>Email</th>
                            <th>Summoner Name</th>
                            <th>Price</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr class="tableVisibleRow">
                                <td>#{{ $order->id }}</td>
                                <td>{{ $order->created_at->format('d/m/y') }}</td>
                                <td>
                                    @switch($order->queue_type)
                                        @case(1)
                                        Solo
                                        @break
                                        @case(2)
                                        Duo
                                        @break
                                        @case(3)
                                        Solo (flex)
                                        @break
                                        @case(4)
                                        Duo (flex)
                                        @break
                                    @endswitch
                                </td>
                                @if($order->current_rank && $order->desired_rank)
                                    <td>
                                        {{ $order->currentRank->rankTier->name }}
                                        {{ $order->currentRank->rankDivision->number }}
                                        ->
                                        {{ $order->desiredRank->rankTier->name }}
                                        {{ $order->desiredRank->rankDivision->number }}
                                    </td>
                                @elseif($order->boost_type == 2)
                                    <td>{{ $order->wins }} Placements ({{ $order->currentRank->rankTier->name }} {{ $order->currentRank->rankDivision->number }})</td>
                                @else
                                    <td>{{ $order->wins }} Net Wins ({{ $order->currentRank->rankTier->name }} {{ $order->currentRank->rankDivision->number }})</td>
                                @endif
                                <td>{{ $order->summoner_name }}</td>
                                <td>${{ $order->price }}</td>
                                <td>N/A</td>
                                <td>
                                    <a href="#" class="btn btn-outline-info btn-sm dropdown-toggle orderExtras">Extras</a>
                                </td>
                            </tr>
                            <tr class="tableHiddenRow" style="background-color: #f5f5f5;">
                                <th colspan="3">
                                    Roles:
                                </th>
                                <th colspan="3">
                                    Spells:
                                </th>
                                <th colspan="3">
                                    Addons:
                                </th>
                            </tr>
                            <tr>
                                <td colspan="3">
                                    @if($order->orderExtra->role1)
                                        {{ $order->orderExtra->role1 }} | {{ $order->orderExtra->role2 }}
                                    @endif
                                </td>
                                <td colspan="3">
                                    @if($order->orderExtra->spell1)
                                        [D] {{ $order->orderExtra->spell1 }} | [F] {{ $order->orderExtra->spell2 }}
                                    @endif
                                </td>
                                <td colspan="3">
                                    <ul>
                                        @if($order->orderExtra->premium)<li>Premium</li>@endif
                                        @if($order->orderExtra->streaming)<li>Streaming</li>@endif
                                        @if($order->orderExtra->offline)<li>Offline Mode</li>@endif
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>


    <div class="row">
        <div class="col-6">
            <form method="post" action="{{ route('admin.orders.destroy', ['order' => $order->id]) }}">
                @csrf
                @method('DELETE')

                <p>Are you sure you wish to delete this order?</p>


                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </div>

    <script>
        (function () {
            let orderExtraButtons = document.querySelectorAll('.orderExtras');
            orderExtraButtons.forEach(function(element) {
                element.addEventListener('click', function(e) {
                    e.preventDefault();
                    let hiddenRow = element.parentElement.parentElement.nextElementSibling;

                    if(!hiddenRow.classList.contains('tableHiddenRow')) {
                        hiddenRow.classList.add('tableHiddenRow');
                    }else {
                        hiddenRow.classList.remove('tableHiddenRow');
                    }
                });
            });
        })();
    </script>


</x-app-layout>

resources/views/dashboard/orders-finished.blade.php
<x-app-layout>
    @push('styles')
        <style>
            .tableHiddenRow, .tableHiddenRow + tr {
                display: none;
            }
        </style>
    @endpush
    <x-slot name="header">
            Orders
    </x-slot>


    @if (session('status'))
        <div class="row">
            <div class="col-xl-12 col-md-12 mb-4">
                <div class="alert alert-success" role="alert">
                    {{ session('status') }}
                </div>
            </div>
        </div>
    @endif
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <a href="{{ route('admin.orders.index') }}">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Open Orders</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $openOrderCount }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
                </a>
            </div>
        </div>

        <!-- Earnings (Annual) Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <a href="{{ route('admin.boosts.index') }}">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Orders Processesing</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $boostsCount }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
                </a>
            </div>
        </div>

        <!-- Pending Requests Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <a href="{{ route('admin.orders.finished') }}">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Finished Orders</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $finishedBoostsCount }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        <!-- DataTales Example -->
        <div class="card shadow col-xl-10 col-md-6 mb-4 px-0 mx-3">
            <div class="card-header py-3 d-flex justify-content-between align-items-baseline">
                <h6 class="m-0 font-weight-bold text-primary">Open Orders</h6>
                <a href="{{ route('admin.orders.create') }}" class="btn btn-primary">Create Order</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Booster</th>
                            <th>Date</th>
                            <th>Queue</th>
                            <th>Boost</th>
                            <th>Email</th>
                            <th>Summoner Name</th>
                            <th>Price</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Booster</th>
                            <th>Date</th>
                            <th>Queue</th>
                            <th>Boost</th>
                            <th>Email</th>
                            <th>Summoner Name</th>
                            <th>Price</th>
                            <th>Actions</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @foreach($orders as $order)
                        <tr class="tableVisibleRow">
                            <td>#{{ $order->id }}</td>
                            <td>{{ $order->boosts()->where('status', 2)->first()->user->name }}</td>
                            <td>{{ $order->created_at->format('d/m/y') }}</td>
                            <td>
                                @switch($order->queue_type)
                                    @case(1)
                                    Solo
                                    @break
                                    @case(2)
                                    Duo
                                    @break
                                    @case(3)
                                    Solo (flex)
                                    @break
                                    @case(4)
                                    Duo (flex)
                                    @break
                                @endswitch
                            </td>
                            @if($order->current_rank && $order->desired_rank)
                                <td>
                                    {{ $order->currentRank->rankTier->name }}
                                    {{ $order->currentRank->rankDivision->number }}
                                    ->
                                    {{ $order->desiredRank->rankTier->name }}
                                    {{ $order->desiredRank->rankDivision->number }}
                                </td>
                            @elseif($order->boost_type == 2)
                                <td>{{ $order->wins }} Placements ({{ $order->currentRank->rankTier->name }} {{ $order->currentRank->rankDivision->number }})</td>
                            @else
                                <td>{{ $order->wins }} Net Wins ({{ $order->currentRank->rankTier->name }} {{ $order->currentRank->rankDivision->number }})</td>
                            @endif
                            <td>{{ $order->email }}</td>
                            <td>{{ $order->summoner_name }}</td>
                            <td>${{ $order->price }}</td>
                            <td>
                                <a href="{{ route('admin.orders.delete', ['order' => $order->id]) }}" class="btn btn-outline-danger btn-sm mr-2">Delete</a>
                                -
                                <a href="#" class="btn btn-outline-info btn-sm dropdown-toggle ml-2 orderExtras">Extras</a>
                            </td>
                        </tr>
                        <tr class="tableHiddenRow" style="background-color: #f5f5f5;">
                            <th colspan="4">
                                Login:
                            </th>
                            <th colspan="2">
                                Roles:
                            </th>
                            <th colspan="1">
                                Spells:
                            </th>
                            <th colspan="2">
                                Addons:
                            </th>
                        </tr>
                        <tr>
                            <td colspan="4">
                                User: {{ $order->username }}<br />
                                Pass: {{ $order->password }}
                            </td>
                            <td colspan="2">
                                @if($order->orderExtra->role1)
                                    {{ $order->orderExtra->role1 }} | {{ $order->orderExtra->role2 }}
                                @endif
                            </td>
                            <td colspan="1">
                                @if($order->orderExtra->spell1)
                                    [D] {{ $order->orderExtra->spell1 }} | [F] {{ $order->orderExtra->spell2 }}
                                @endif
                            </td>
                            <td colspan="2">
                                <ul>
                                    @if($order->orderExtra->premium)<li>Premium</li>@endif
                                    @if($order->orderExtra->streaming)<li>Streaming</li>@endif
                                    @if($order->orderExtra->offline)<li>Offline Mode</li>@endif
                                </ul>
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

    <script>
        (function () {
            let orderExtraButtons = document.querySelectorAll('.orderExtras');
            orderExtraButtons.forEach(function(element) {
                element.addEventListener('click', function(e) {
                    e.preventDefault();
                    let hiddenRow = element.parentElement.parentElement.nextElementSibling;

                    if(!hiddenRow.classList.contains('tableHiddenRow')) {
                        hiddenRow.classList.add('tableHiddenRow');
                    }else {
                        hiddenRow.classList.remove('tableHiddenRow');
                    }
                });
            });
        })();
    </script>

</x-app-layout>